fix merge

diff --git a/.github/workflows/config-values.yaml b/.github/workflows/config-values.yaml
--- a/.github/workflows/config-values.yaml
+++ b/.github/workflows/config-values.yaml
@@ -10,12 +10,16 @@ on:
       - 'charts/**'
       - 'infra/**'
       - '**/infra/**'
+      - 'libs/auth/scopes/src/lib/clients/**'
+      - '.github/**'
   workflow_dispatch: {}
   pull_request:
     paths:
       - 'charts/**'
       - 'infra/**'
       - '**/infra/**'
+      - 'libs/auth/scopes/src/lib/clients/**'
+      - '.github/**'
 
 defaults:
   run:
@@ -23,13 +27,13 @@ defaults:
 
 env:
   AWS_MAX_ATTEMPTS: 10
+  AWS_REGION: eu-west-1
   GITHUB_ACTIONS_CACHE_URL: https://cache.dev01.devland.is/
+  RUNS_ON_BUCKET_NAME: ${{ vars.RUNS_ON_BUCKET_NAME }}
 
 jobs:
   prepare:
-    runs-on: ec2-runners
-    container:
-      image: public.ecr.aws/m3u4c4h9/island-is/actions-runner-public:latest
+    runs-on: arc-shared
     outputs:
       ENVS: ${{ steps.select_envs.outputs.ENVS }}
     steps:
@@ -48,45 +52,29 @@ jobs:
           echo "ENVS={\"env\":$ENVS_JSON}" >> "$GITHUB_OUTPUT"
 
   helm-values-validation:
-    runs-on: ec2-runners
-    container:
-      image: public.ecr.aws/m3u4c4h9/island-is/actions-runner-public:latest
-    timeout-minutes: 5
+    runs-on: arc-shared
+    timeout-minutes: 25
     steps:
       - uses: actions/checkout@v4
-        if: ${{ github.event_name == 'pull_request' }}
+        if: ${{ github.event_name == 'pull_request' && !github.event.localrun }}
         with:
           ref: ${{ github.event.pull_request.head.ref }}
-          token: ${{ secrets.DIRTY_FIX_BOT_TOKEN }}
+          persist-credentials: false
 
       - uses: actions/checkout@v4
-        if: ${{ github.event_name != 'pull_request' }}
-
-      - uses: actions/setup-node@v4
-        with:
-          node-version-file: 'package.json'
+        if: ${{ github.event_name != 'pull_request' || github.event.localrun }}
 
       - name: Setup yarn
-        run: corepack enable
+        uses: ./.github/actions/setup-yarn
 
-      - name: Cache for NodeJS dependencies
-        id: node-modules
-        continue-on-error: true
-        uses: ./.github/actions/cache
+      - name: Setup yarn (infra)
+        uses: ./.github/actions/setup-yarn
         with:
-          path: infra/node_modules
-          key: ${{ runner.os }}-${{ hashFiles('infra/yarn.lock') }}-infra-2
-
-      - name: Check cache success
-        run: '[[ "${{ steps.node-modules.outputs.success }}" != "false" ]] || exit 1'
-
-      - name: Building NodeJS dependencies
-        if: steps.node-modules.outputs.cache-hit != 'true'
-        working-directory: infra
-        run: yarn install --immutable
+          working-directory: infra
 
       - name: Run unit tests
-        run: ./infra/scripts/ci/test-unit.sh
+        working-directory: infra
+        run: yarn test
 
       - name: Check chart values are up-to-date
         if: ${{ github.ref == 'ref/heads/main' }}
@@ -94,41 +82,30 @@ jobs:
 
       - name: Commit any changes to charts
         if: ${{ github.event_name == 'pull_request' }}
+        env:
+          DIRTYBOT_KEY: ${{ secrets.ISLAND_IS_SSH_KEY }}
+          DIRTYBOT_APP_ID: ${{ secrets.ISLAND_IS_APP_KEY }}
         run: |
           (cd infra && yarn charts)
-          ./infra/scripts/ci/git-check-dirty.sh "charts/" "charts" "dirtybot"
+          node scripts/ci/docker/git-check-dirty.mjs "charts/" "charts" "dirtybot"
 
   check-secrets:
     needs:
       - prepare
       - helm-values-validation # waiting on this job so the cache would be prepared
-    runs-on: ec2-runners
-    container:
-      image: public.ecr.aws/m3u4c4h9/island-is/actions-runner-public:latest
+    runs-on: arc-shared
     strategy:
       fail-fast: false
       matrix: ${{ fromJson(needs.prepare.outputs.ENVS) }}
     steps:
       - uses: actions/checkout@v4
-      - uses: actions/setup-node@v4
+      - name: Setup yarn
+        uses: ./.github/actions/setup-yarn
+
+      - name: Setup yarn (infra)
+        uses: ./.github/actions/setup-yarn
         with:
-          node-version-file: 'package.json'
-
-      - name: Cache for NodeJS dependencies
-        id: node-modules
-        continue-on-error: true
-        uses: ./.github/actions/cache
-        with:
-          path: infra/node_modules
-          key: ${{ runner.os }}-${{ hashFiles('infra/yarn.lock') }}-infra
-
-      - name: Check cache success
-        run: '[[ "${{ steps.node-modules.outputs.success }}" != "false" ]] || exit 1'
-
-      - name: Building NodeJS dependencies
-        if: steps.node-modules.outputs.cache-hit != 'true'
-        working-directory: infra
-        run: yarn install --immutable
+          working-directory: infra
 
       - name: Select role
         env:
@@ -181,3 +158,20 @@ jobs:
             while IFS= read -r secret ; do echo $secret; done <<< "$missing"
             exit 1
           fi
+
+  success:
+    name: Config Values Success
+    if: ${{ !cancelled() }}
+    needs:
+      - check-secrets
+    runs-on: arc-shared
+    steps:
+      - name: Collect
+        run: |
+          for job in ${{ needs.check-secrets.result }}; do
+            if [[ "$job" == "failure" ]]; then
+              echo "::error title=config values::❌ config values workflow failed!"
+              exit 1
+            fi
+          done
+          echo "::info title=config values::✅ config values workflow ran successfully."
