chore(ci): Add config values collector (#19286)
* Add regionAdd region for Config Values

* Add success step and job to Config Values

* DEPLOYME

* Affect infra/, but only via versioning

* Always run collector

diff --git a/.github/workflows/config-values.yaml b/.github/workflows/config-values.yaml
--- a/.github/workflows/config-values.yaml
+++ b/.github/workflows/config-values.yaml
@@ -151,3 +151,20 @@ jobs:
             while IFS= read -r secret ; do echo $secret; done <<< "$missing"
             exit 1
           fi
+
+  success:
+    name: Config Values Success
+    if: ${{ !cancelled() }}
+    needs:
+      - check-secrets
+    runs-on: arc-shared
+    steps:
+      - name: Collect
+        run: |
+          for job in ${{ needs.check-secrets.result }}; do
+            if [[ "$job" == "failure" ]]; then
+              echo "::error title=config values::❌ config values workflow failed!"
+              exit 1
+            fi
+          done
+          echo "::info title=config values::✅ config values workflow ran successfully."
