Updated conditional failure

diff --git a/.github/workflows/e2e.yml b/.github/workflows/e2e.yml
--- a/.github/workflows/e2e.yml
+++ b/.github/workflows/e2e.yml
@@ -73,14 +73,10 @@ jobs:
         uses: ./.github/actions/setup-playwright
 
       - name: Running e2e tests
-        continue-on-error: ${{ inputs.allow_failure && inputs.allow_failure == 'true' }}
         env:
           ALLOW_FAILURE: ${{ inputs.allow_failure && inputs.allow_failure == 'true' }}
         run: |
           if ! yarn nx run-many --target=e2e --projects="${AFFECTED_PROJECTS}" --parallel 3 ; then
-            if [[ "$ALLOW_FAILURE" == true ]]; then
-              echo "::error title=e2e::Some of ${AFFECTED_PROJECTS} failed e2e tests"
-            else
-              exit 1
-            fi
+            echo "::error title=e2e::Project ${AFFECTED_PROJECTS} failed e2e tests"
+            exit "${{ inputs.allow_failure == 'true' && 0 || exit 1 }}
           fi
