Revert merge-queue.yml to main

diff --git a/.github/workflows/merge-queue.yml b/.github/workflows/merge-queue.yml
--- a/.github/workflows/merge-queue.yml
+++ b/.github/workflows/merge-queue.yml
@@ -3,14 +3,9 @@ name: Validate code in the merge queue (post merge)
 on:
   workflow_dispatch: {}
   merge_group:
-  # pull_request:
-  #   # For debugging with 'ci debug' label
-  #   types:
-  #     - synchronize
-  #     - labeled
 defaults:
   run:
-    shell: bash -euo pipefail {0}
+    shell: bash -euxo pipefail {0}
 
 concurrency:
   group: merge-queue-post-${{ github.head_ref || github.run_id }}
@@ -27,80 +22,182 @@ env:
   MAX_JOBS: ${{ vars.MAX_JOBS || 2 }}
   NX_PARALLEL: ${{ vars.NX_PARALLEL || 2 }}
   NX_MAX_PARALLEL: ${{ vars.NX_MAX_PARALLEL || 4 }}
-  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
-  NX_TASKS_RUNNER: ci
 
 jobs:
-  prepare:
-    if: ${{ github.event_name != 'pull_request' || contains(github.event.pull_request.labels.*.name, 'ci debug') }}
-    runs-on: arc-runners
-    outputs:
-      affected: ${{ steps.affected.outputs.build-chunks }}
-      nx: ${{ steps.affected.outputs.nx }}
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-      - uses: actions/setup-node@v4
-        with:
-          node-version-file: 'package.json'
-          cache: yarn
-      - name: Get cache
-        id: get_cache
-        uses: ./.github/actions/get-cache
-        with:
-          github-token: ${{ github.token }}
-          enable-cache: node_modules
-      - name: Derive appropriate SHAs
-        if: ${{ !github.event.localrun }}
-        uses: nrwl/nx-set-shas@v4
-      - name: Setup yarn
-        run: |
-          ls -lahd node_modules
-          # Cached by GitHub actions
-          corepack enable
-          # Cached by `get-cache` above
-          yarn install --immutable
-      - name: Find affected projects
-        id: affected
-        env:
-          BASE: ${{ env.NX_BASE || env.GITHUB_BASE_REF || github.event.pull_request.base.sha }}
-          HEAD: ${{ env.NX_HEAD || env.GITHUB_HEAD_REF || github.event.pull_request.head.sha }}
-          is_debug: ${{ contains(github.event.pull_request.labels.*.name, 'ci debug') }}
-        run: |
-          if [[ "$is_debug" == true ]]; then
-            chunks='build-chunks=["web","air-discount-scheme-api,air-discount-scheme-backend,air-discount-scheme-web","license-api","system-e2e","island-ui-storybook"]'
-          else
-            chunks="$(./scripts/ci/generate-chunks.sh build)"
-          fi
-          echo "build-chunks={\"projects\":$chunks}" | tee -a "$GITHUB_OUTPUT"
-          echo "nx={\"parallel\":${{ env.NX_PARALLEL }},\"max-parallel\":${{ env.NX_MAX_PARALLEL }}}" | tee -a "$GITHUB_OUTPUT"
+  # prepare:
+  #   runs-on: arc-runners
+  #   timeout-minutes: 35
+  #   env:
+  #     AFFECTED_ALL: ${{ secrets.AFFECTED_ALL }}
+  #     SERVERSIDE_FEATURES_ON: ''
+  #     DOCKER_REGISTRY: 821090935708.dkr.ecr.eu-west-1.amazonaws.com/
 
-  docker-build:
-    uses: ./.github/workflows/docker.yml
-    secrets: inherit
+  #   outputs:
+  #     CACHE_KEYS: ${{ steps.get_cache.outputs.keys }}
+  #     TEST_CHUNKS: ${{ steps.build_info.outputs.TEST_CHUNKS }}
+  #     E2E_CHUNKS: ${{ steps.build_info.outputs.E2E_CHUNKS }}
+  #     E2E_BUILD_ID: ${{ steps.build_info.outputs.BUILD_ID }}
+  #     BUILD_CHUNKS: ${{ steps.build_info.outputs.BUILD_CHUNKS }}
+  #   steps:
+  #     - name: Checkout code
+  #       uses: actions/checkout@v4
+  #       with:
+  #         fetch-depth: 0
+
+  #     - uses: actions/setup-node@v4
+  #       with:
+  #         node-version-file: 'package.json'
+
+  #     - name: Setup yarn
+  #       run: corepack enable
+
+  #     - name: Get cache
+  #       id: get_cache
+  #       uses: ./.github/actions/get-cache
+  #       with:
+  #         github-token: ${{ secrets.GITHUB_TOKEN }}
+  #         enable-cache: 'node_modules,cypress'
+
+  #     - name: Derive appropriate SHAs
+  #       uses: nrwl/nx-set-shas@v4
+
+  #     - name: Gather branch info
+  #       id: build_info
+  #       run: |
+  #         export BASE=${{ env.NX_BASE }}
+  #         export HEAD=${{ env.NX_HEAD }}
+
+  #         echo "TEST_CHUNKS={\"projects\":$(./scripts/ci/generate-chunks.sh test)}" >> "$GITHUB_OUTPUT"
+  #         echo "BUILD_CHUNKS={\"projects\":$(./scripts/ci/generate-chunks.sh build)}" >> "$GITHUB_OUTPUT"
+  #         echo "E2E_CHUNKS={\"projects\":$(./scripts/ci/generate-chunks.sh e2e-ci)}" >> "$GITHUB_OUTPUT"
+  #         echo BUILD_ID="$GITHUB_RUN_ID-$GITHUB_RUN_NUMBER-$(uuidgen)" >> "$GITHUB_OUTPUT"
+
+  # tests:
+  #   needs:
+  #     - prepare
+  #   if: needs.prepare.outputs.TEST_CHUNKS
+  #   runs-on: ec2-runners
+  #   container:
+  #     image: public.ecr.aws/m3u4c4h9/island-is/actions-runner-public:latest
+  #   env:
+  #     AFFECTED_PROJECTS: ${{ matrix.projects }}
+  #   strategy:
+  #     fail-fast: false
+  #     matrix: ${{ fromJson(needs.prepare.outputs.TEST_CHUNKS) }}
+  #   steps:
+  #     - uses: actions/checkout@v4
+
+  #     - uses: actions/setup-node@v4
+  #       with:
+  #         node-version-file: 'package.json'
+
+  #     - name: Setup yarn
+  #       run: corepack enable
+
+  #     - name: Get cache
+  #       id: get-cache
+  #       uses: ./.github/actions/get-cache
+  #       with:
+  #         github-token: ${{ secrets.GITHUB_TOKEN }}
+  #         keys: ${{ needs.prepare.outputs.CACHE_KEYS }}
+  #         enable-cache: 'node_modules,cypress'
+
+  #     - uses: ./.github/actions/unit-test
+  #       with:
+  #         dd-api-key: '${{ secrets.DD_API_KEY }}'
+  #         codecov-token: ${{ secrets.CODECOV_TOKEN }}
+  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+  #         docker-registry: 821090935708.dkr.ecr.eu-west-1.amazonaws.com/
+
+  # e2e:
+  #   needs:
+  #     - prepare
+  #   if: needs.prepare.outputs.E2E_CHUNKS
+  #   runs-on: arc-runners
+  #   timeout-minutes: 45
+  #   env:
+  #     AFFECTED_PROJECT: ${{ matrix.projects }}
+  #     CYPRESS_PROJECT_ID: 4q7jz8
+  #     CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
+  #     API_MOCKS: 'true'
+  #     NODE_OPTIONS: --max-old-space-size=4096
+  #     E2E_BUILD_ID: '${{ needs.prepare.outputs.E2E_BUILD_ID }}-${{ github.run_attempt }}'
+  #   strategy:
+  #     fail-fast: false
+  #     matrix: ${{ fromJson(needs.prepare.outputs.E2E_CHUNKS) }}
+  #   steps:
+  #     - uses: actions/checkout@v4
+
+  #     - uses: actions/setup-node@v4
+  #       with:
+  #         node-version-file: 'package.json'
+
+  #     - name: Setup yarn
+  #       run: corepack enable
+
+  #     - name: Get cache
+  #       id: get-cache
+  #       uses: ./.github/actions/get-cache
+  #       with:
+  #         github-token: ${{ secrets.GITHUB_TOKEN }}
+  #         keys: ${{ needs.prepare.outputs.CACHE_KEYS }}
+  #         enable-cache: 'node_modules,cypress'
+
+  #     - name: Running e2e tests
+  #       run: ./scripts/ci/40_e2e.sh "${AFFECTED_PROJECT}"
+
+  # build:
+  #   needs:
+  #     - prepare
+  #   runs-on: arc-runners
+  #   timeout-minutes: 35
+  #   env:
+  #     AFFECTED_PROJECTS: ${{ matrix.projects }}
+  #   strategy:
+  #     fail-fast: true
+  #     matrix: ${{ fromJson(needs.prepare.outputs.BUILD_CHUNKS) }}
+  #   if: needs.prepare.outputs.BUILD_CHUNKS
+  #   steps:
+  #     - uses: actions/checkout@v4
+  #     - uses: actions/setup-node@v4
+  #       with:
+  #         node-version-file: 'package.json'
+  #     - name: Setup yarn
+  #       run: corepack enable
+  #     - name: Get cache
+  #       id: get-cache
+  #       uses: ./.github/actions/get-cache
+  #       with:
+  #         github-token: ${{ secrets.GITHUB_TOKEN }}
+  #         keys: ${{ needs.prepare.outputs.CACHE_KEYS }}
+  #         enable-cache: 'node_modules'
+
+  #     - name: Building
+  #       run: ./scripts/ci/run-in-parallel-native.sh build
 
   success:
     runs-on: arc-runners
-    needs:
-      - docker-build
-    env:
-      needs_results: ${{ needs.*.result }}
-      needs: ${{ needs }}
+    # if: ${{ !cancelled() }}
+    # needs:
+    #   - prepare
+    #   - tests
+    #   - e2e
+    #   - build
     steps:
-      - run: |
-          set -x
-          echo "$needs_results"
-          echo "$needs" | jq -ne '[.[] | select(.result != "success") ] | length == 0'
-      - name: Check docker-build success
-        run: '[[ ${{ needs.prepare.result }} == "success" ]] || exit 1'
       - name: Announce success
         run: echo "Build is successful"
+      # - name: Check prepare success
+      #   run: '[[ ${{ needs.prepare.result }} == "success" ]] || exit 1'
+      # - name: Check tests success
+      #   run: '[[ ${{ needs.tests.result }} != "failure" ]] || exit 1'
+      # - name: Check e2e success
+      #   run: '[[ ${{ needs.e2e.result }} != "failure" ]] || exit 1'
+      # - name: Check build success
+      #   run: '[[ ${{ needs.build.result }} != "failure" ]] || exit 1'
 
   # Remove this as a required status check and switch to something more meaningful
   codeowners-check:
-    if: false
     name: Lint CODEOWNERS
     runs-on: arc-runners
     env:
