feat(ci): revert merge queues (#18004)
Revert "feat(ci): merge queues (#17913)"

This reverts commit 514a219f18d2f4d9817b12562e43b748df393e13.

diff --git a/.github/workflows/merge-queue.yml b/.github/workflows/merge-queue.yml
--- a/.github/workflows/merge-queue.yml
+++ b/.github/workflows/merge-queue.yml
@@ -3,7 +3,6 @@ name: Validate code in the merge queue (post merge)
 on:
   workflow_dispatch: {}
   merge_group:
-
 defaults:
   run:
     shell: bash -euxo pipefail {0}
@@ -13,89 +12,185 @@ concurrency:
   cancel-in-progress: true
 
 env:
-  DOCKER_REGISTRY: 821090935708.dkr.ecr.eu-west-1.amazonaws.com
-  DOCKER_BASE_IMAGE_REGISTRY: 821090935708.dkr.ecr.eu-west-1.amazonaws.com/ecr-public
-  SPINNAKER_URL: https://spinnaker-gate.shared.devland.is
   COMPOSE_HTTP_TIMEOUT: 180
-  GITHUB_ACTIONS_CACHE_URL: https://cache.dev01.devland.is/
   SKIP_GENERATED_CACHE: ${{ contains(github.event.pull_request.labels.*.name, 'skip-generated-cache') }}
   NX_AFFECTED_ALL: ${{ contains(github.event.pull_request.labels.*.name, 'nx-affected-all') }}
-  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
-  NX_TASKS_RUNNER: ci
-  CONFIGCAT_MAIN_CONFIG_ID: 08d8c761-021c-46f0-8671-6244663a372f
-  CONFIGCAT_MOBILE_APP_CONFIG_ID: 08daf234-7573-4b3b-85f6-189fc7502542
-  DISABLE_CHUNKS: 'false'
-  DISABLE_GROUPING: 'false'
-  DISABLE_PROBLEMATIC: 'false'
-  CHUNK_SIZE: '3'
-  MAX_JOBS: '2'
-  NX_PARALLEL: '2'
-  NX_MAX_PARALLEL: '4'
-  NODE_IMAGE_VERSION: 20
-  S3_DOCKER_CACHE_BUCKET: ${{ secrets.S3_DOCKER_CACHE_BUCKET }}
-  RUNS_ON_S3_BUCKET_CACHE: ${{ secrets.S3_DOCKER_CACHE_BUCKET }}
-  YARN_ENABLE_HARDENED_MODE: '0'
-  AWS_REGION: eu-west-1
-  AFFECTED_ALL: ${{ secrets.AFFECTED_ALL }}
-  SERVERSIDE_FEATURES_ON: ''
-  GENERATED_FILES: ${{ github.workspace }}/${{ github.sha }}.tar.gz
+  CHUNK_SIZE: ${{ vars.CHUNK_SIZE || 3 }}
+  DISABLE_GROUPING: ${{ vars.DISABLE_GROUPING || false }}
+  DISABLE_CHUNKS: ${{ vars.DISABLE_CHUNKS || false }}
+  DISABLE_PROBLEMATIC: ${{ vars.DISABLE_PROBLEMATIC || false }}
+  MAX_JOBS: ${{ vars.MAX_JOBS || 2 }}
+  NX_PARALLEL: ${{ vars.NX_PARALLEL || 2 }}
+  NX_MAX_PARALLEL: ${{ vars.NX_MAX_PARALLEL || 4 }}
 
 jobs:
-  pre-checks:
-    uses: ./.github/workflows/pre-checks.yml
-    secrets: inherit
-  prepare:
-    uses: ./.github/workflows/install.yml
-    secrets: inherit
-    needs:
-      - pre-checks
+  # prepare:
+  #   runs-on: arc-runners
+  #   timeout-minutes: 35
+  #   env:
+  #     AFFECTED_ALL: ${{ secrets.AFFECTED_ALL }}
+  #     SERVERSIDE_FEATURES_ON: ''
+  #     DOCKER_REGISTRY: 821090935708.dkr.ecr.eu-west-1.amazonaws.com/
 
-  tests:
-    needs:
-      - prepare
-    if: ${{ needs.prepare.outputs.TEST_CHUNKS && needs.prepare.outputs.DEPLOY_FEATURE == 'false' }}
-    runs-on: arc-runners
-    timeout-minutes: 45
-    env:
-      AFFECTED_PROJECTS: ${{ matrix.projects }}
-      NX_BASE: ${{ needs.prepare.outputs.NX_BASE }}
-    strategy:
-      fail-fast: false
-      matrix: ${{ fromJson(needs.prepare.outputs.TEST_CHUNKS) }}
-    steps:
-      - name: checkout
-        uses: actions/checkout@v4
+  #   outputs:
+  #     CACHE_KEYS: ${{ steps.get_cache.outputs.keys }}
+  #     TEST_CHUNKS: ${{ steps.build_info.outputs.TEST_CHUNKS }}
+  #     E2E_CHUNKS: ${{ steps.build_info.outputs.E2E_CHUNKS }}
+  #     E2E_BUILD_ID: ${{ steps.build_info.outputs.BUILD_ID }}
+  #     BUILD_CHUNKS: ${{ steps.build_info.outputs.BUILD_CHUNKS }}
+  #   steps:
+  #     - name: Checkout code
+  #       uses: actions/checkout@v4
+  #       with:
+  #         fetch-depth: 0
 
-      - name: Setup yarn
-        uses: ./.github/actions/setup-yarn
+  #     - uses: actions/setup-node@v4
+  #       with:
+  #         node-version-file: 'package.json'
 
-      - name: load-deps
-        uses: ./.github/actions/load-deps
+  #     - name: Setup yarn
+  #       run: corepack enable
 
-      - name: Run unit tests
-        uses: ./.github/actions/unit-test
-        with:
-          dd-api-key: '${{ secrets.DD_API_KEY }}'
-          codecov-token: ${{ secrets.CODECOV_TOKEN }}
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          docker-registry: 821090935708.dkr.ecr.eu-west-1.amazonaws.com/
+  #     - name: Get cache
+  #       id: get_cache
+  #       uses: ./.github/actions/get-cache
+  #       with:
+  #         github-token: ${{ secrets.GITHUB_TOKEN }}
+  #         enable-cache: 'node_modules,cypress'
+
+  #     - name: Derive appropriate SHAs
+  #       uses: nrwl/nx-set-shas@v4
+
+  #     - name: Gather branch info
+  #       id: build_info
+  #       run: |
+  #         export BASE=${{ env.NX_BASE }}
+  #         export HEAD=${{ env.NX_HEAD }}
+
+  #         echo "TEST_CHUNKS={\"projects\":$(./scripts/ci/generate-chunks.sh test)}" >> "$GITHUB_OUTPUT"
+  #         echo "BUILD_CHUNKS={\"projects\":$(./scripts/ci/generate-chunks.sh build)}" >> "$GITHUB_OUTPUT"
+  #         echo "E2E_CHUNKS={\"projects\":$(./scripts/ci/generate-chunks.sh e2e-ci)}" >> "$GITHUB_OUTPUT"
+  #         echo BUILD_ID="$GITHUB_RUN_ID-$GITHUB_RUN_NUMBER-$(uuidgen)" >> "$GITHUB_OUTPUT"
+
+  # tests:
+  #   needs:
+  #     - prepare
+  #   if: needs.prepare.outputs.TEST_CHUNKS
+  #   runs-on: ec2-runners
+  #   container:
+  #     image: public.ecr.aws/m3u4c4h9/island-is/actions-runner-public:latest
+  #   env:
+  #     AFFECTED_PROJECTS: ${{ matrix.projects }}
+  #   strategy:
+  #     fail-fast: false
+  #     matrix: ${{ fromJson(needs.prepare.outputs.TEST_CHUNKS) }}
+  #   steps:
+  #     - uses: actions/checkout@v4
+
+  #     - uses: actions/setup-node@v4
+  #       with:
+  #         node-version-file: 'package.json'
+
+  #     - name: Setup yarn
+  #       run: corepack enable
+
+  #     - name: Get cache
+  #       id: get-cache
+  #       uses: ./.github/actions/get-cache
+  #       with:
+  #         github-token: ${{ secrets.GITHUB_TOKEN }}
+  #         keys: ${{ needs.prepare.outputs.CACHE_KEYS }}
+  #         enable-cache: 'node_modules,cypress'
+
+  #     - uses: ./.github/actions/unit-test
+  #       with:
+  #         dd-api-key: '${{ secrets.DD_API_KEY }}'
+  #         codecov-token: ${{ secrets.CODECOV_TOKEN }}
+  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+  #         docker-registry: 821090935708.dkr.ecr.eu-west-1.amazonaws.com/
+
+  # e2e:
+  #   needs:
+  #     - prepare
+  #   if: needs.prepare.outputs.E2E_CHUNKS
+  #   runs-on: arc-runners
+  #   timeout-minutes: 45
+  #   env:
+  #     AFFECTED_PROJECT: ${{ matrix.projects }}
+  #     CYPRESS_PROJECT_ID: 4q7jz8
+  #     CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
+  #     API_MOCKS: 'true'
+  #     NODE_OPTIONS: --max-old-space-size=4096
+  #     E2E_BUILD_ID: '${{ needs.prepare.outputs.E2E_BUILD_ID }}-${{ github.run_attempt }}'
+  #   strategy:
+  #     fail-fast: false
+  #     matrix: ${{ fromJson(needs.prepare.outputs.E2E_CHUNKS) }}
+  #   steps:
+  #     - uses: actions/checkout@v4
+
+  #     - uses: actions/setup-node@v4
+  #       with:
+  #         node-version-file: 'package.json'
+
+  #     - name: Setup yarn
+  #       run: corepack enable
+
+  #     - name: Get cache
+  #       id: get-cache
+  #       uses: ./.github/actions/get-cache
+  #       with:
+  #         github-token: ${{ secrets.GITHUB_TOKEN }}
+  #         keys: ${{ needs.prepare.outputs.CACHE_KEYS }}
+  #         enable-cache: 'node_modules,cypress'
+
+  #     - name: Running e2e tests
+  #       run: ./scripts/ci/40_e2e.sh "${AFFECTED_PROJECT}"
+
+  # build:
+  #   needs:
+  #     - prepare
+  #   runs-on: arc-runners
+  #   timeout-minutes: 35
+  #   env:
+  #     AFFECTED_PROJECTS: ${{ matrix.projects }}
+  #   strategy:
+  #     fail-fast: true
+  #     matrix: ${{ fromJson(needs.prepare.outputs.BUILD_CHUNKS) }}
+  #   if: needs.prepare.outputs.BUILD_CHUNKS
+  #   steps:
+  #     - uses: actions/checkout@v4
+  #     - uses: actions/setup-node@v4
+  #       with:
+  #         node-version-file: 'package.json'
+  #     - name: Setup yarn
+  #       run: corepack enable
+  #     - name: Get cache
+  #       id: get-cache
+  #       uses: ./.github/actions/get-cache
+  #       with:
+  #         github-token: ${{ secrets.GITHUB_TOKEN }}
+  #         keys: ${{ needs.prepare.outputs.CACHE_KEYS }}
+  #         enable-cache: 'node_modules'
+
+  #     - name: Building
+  #       run: ./scripts/ci/run-in-parallel-native.sh build
 
   success:
     runs-on: arc-runners
-    if: ${{ !cancelled() }}
-    needs:
-      - prepare
-      - tests
-      # - e2e
-      # - build
+    # if: ${{ !cancelled() }}
+    # needs:
+    #   - prepare
+    #   - tests
+    #   - e2e
+    #   - build
     steps:
       - name: Announce success
         run: echo "Build is successful"
-      - name: Check prepare success
-        run: '[[ ${{ needs.prepare.result }} == "success" ]] || exit 1'
-      - name: Check tests success
-        run: '[[ ${{ needs.tests.result }} != "failure" ]] || exit 1'
+      # - name: Check prepare success
+      #   run: '[[ ${{ needs.prepare.result }} == "success" ]] || exit 1'
+      # - name: Check tests success
+      #   run: '[[ ${{ needs.tests.result }} != "failure" ]] || exit 1'
       # - name: Check e2e success
       #   run: '[[ ${{ needs.e2e.result }} != "failure" ]] || exit 1'
       # - name: Check build success
