feat: more debug

diff --git a/.github/workflows/native.yml b/.github/workflows/native.yml
--- a/.github/workflows/native.yml
+++ b/.github/workflows/native.yml
@@ -36,7 +36,10 @@ jobs:
 
       # todo get from secrets
       - name: Generate .env file
-        run: echo "IDENTITYSERVER_ISSUER=https://identity-server.dev01.devland.is\nIDENTITYSERVER_CLIENT_ID=@island.is-app\nIDENTITYSERVER_SCOPES=openid profile api_resource.scope offline_access\nAPI_ENDPOINT=https://beta.dev01.devland.is/api\nBUNDLE_ID_IOS=is.island.app-dev\nBUNDLE_ID_ANDROID=is.island.app" > apps/native/app/.env
+        run: |
+          echo "IDENTITYSERVER_ISSUER=https://identity-server.dev01.devland.is\nIDENTITYSERVER_CLIENT_ID=@island.is-app\nIDENTITYSERVER_SCOPES=openid profile api_resource.scope offline_access\nAPI_ENDPOINT=https://beta.dev01.devland.is/api\nBUNDLE_ID_IOS=is.island.app-dev\nBUNDLE_ID_ANDROID=is.island.app" > apps/native/app/.env
+          cat apps/native/app/.env
+
 
       - name: Install Dependencies
         run: yarn install
@@ -67,5 +70,6 @@ jobs:
       - name: Debug info
         run: |
           find apps/native/app/ios/build | grep Info.plist
-          /usr/libexec/PlistBuddy -c "Print :CFBundleIdentifier" apps/native/app/ios/build/Build/Products/Release-iphonesimulator/IslandApp.app/Info.plist || echo "failure"
+          cat apps/native/app/ios/build/Build/Products/Release-iphonesimulator/IslandApp.app/Info.plist
+          /usr/libexec/PlistBuddy -c "Print" apps/native/app/ios/build/Build/Products/Release-iphonesimulator/IslandApp.app/Info.plist || echo "failure"
       - run: cd apps/native && yarn detox:test:ios
