ci: improve nx agents

diff --git a/.github/workflows/pullrequest-nx-cloud.yml b/.github/workflows/pullrequest-nx-cloud.yml
--- a/.github/workflows/pullrequest-nx-cloud.yml
+++ b/.github/workflows/pullrequest-nx-cloud.yml
@@ -37,43 +37,45 @@ env:
   NX_CLOUD_DISTRIBUTED_EXECUTION: true
   NX_CLOUD_DISTRIBUTED_EXECUTION_AGENT_COUNT: 3
 jobs:
-  nx:
+  set-agents:
+    runs-on: ec2-runners
+    container:
+      image: public.ecr.aws/m3u4c4h9/island-is/actions-runner-public:latest
+    name: Set agents
+    # GitHub's default timeout is 360 minutes
+    timeout-minutes: 360
+    outputs:
+      matrix: ${{ steps.set-matrix.outputs.matrix }}
+    if: contains(github.event.pull_request.labels.*.name, 'nx-cloud')
+    steps:
+      - id: set-matrix
+        shell: bash
+        # Turn the number-of-agents input into a JSON structure which is compatible with a Github job matrix strategy
+        run: |
+          AGENTS_JSON_ARRAY=$(node -e "console.log(JSON.stringify(Array.from(new Array(3)).map((_, i) => i + 1)));")
+          echo $AGENTS_JSON_ARRAY
+          echo "matrix=$AGENTS_JSON_ARRAY" >> $GITHUB_OUTPUT
+
+  nx-cloud-agents:
+    needs: set-agents
     runs-on: ec2-runners
     container:
       image: public.ecr.aws/m3u4c4h9/island-is/actions-runner-public:latest
     timeout-minutes: 30
     strategy:
-      fail-fast: false
-      # matrix:
-      #   nx-target:
-      #     - build
-      #     - lint
+      matrix:
+        agent:
+          - ${{fromJson(needs.set-agents.outputs.matrix)}}
+    defaults:
+      run:
+        working-directory: ${{ github.workspace }}
+        # Specify shell to help normalize across different operating systems
+        shell: bash
     if: contains(github.event.pull_request.labels.*.name, 'nx-cloud')
     steps:
       - uses: actions/checkout@v3
         with:
           fetch-depth: 0
-      # - name: Generate matrix output
-      #   run: |
-      #     matrix=$((
-      #       echo '${{ toJSON(matrix) }}'
-      #     ) | jq -c .)
-      #     echo "$matrix" > matrix
-      #     echo "matrix: $matrix"
-      #     echo "::set-output name=matrix::$matrix"
-      #   id: matrix
-      # - name: Upload matrix
-      #   uses: actions/upload-artifact@v3
-      #   id: upload-matrix
-      #   with:
-      #     name: ${{ hashFiles('matrix') || 'none' }}
-      #     path: matrix
-      #     if-no-files-found: warn
-      # - uses: actions/upload-artifact@v3
-      #   with:
-      #     name: ${{ hashFiles('matrix') || 'none' }}
-      #     path: matrix
-      #     if-no-files-found: warn
       - uses: nrwl/nx-set-shas@v3
       - run: |
           echo "BASE=$NX_BASE" >> $GITHUB_ENV
@@ -135,31 +137,33 @@ jobs:
       - name: Untar generated files
         run: tar zxvf generated_files.tar.gz
 
-      - name: Building
-        run: |
-          ./scripts/ci/run-nx-affected.sh ${{ env.NX_TARGETS }}
+      - name: Start Nx Agent ${{ matrix.agent }}
+        run: npx nx-cloud start-agent
+        env:
+          NX_AGENT_NAME: ${{matrix.agent}}
 
-      - name: Stop all running agents for this CI run
-        # It's important that we always run this step, otherwise in the case of any failures in preceding non-Nx steps, the agents will keep running and waste billable minutes
-        if: ${{ always() }}
-        run: npx nx-cloud stop-all-agents
+      # - name: Building
+      #   run: |
+      #     ./scripts/ci/run-nx-affected.sh ${{ env.NX_TARGETS }}
 
-      - name: fix hanging post job
-        run: git config --local --get remote.origin.url
+      # - name: Stop all running agents for this CI run
+      #   # It's important that we always run this step, otherwise in the case of any failures in preceding non-Nx steps, the agents will keep running and waste billable minutes
+      #   if: ${{ always() }}
+      #   run: npx nx-cloud stop-all-agents
 
-  agents:
-    name: Agent
+      # - name: fix hanging post job
+      #   run: git config --local --get remote.origin.url
+  nx-cloud-main:
     runs-on: ec2-runners
     container:
       image: public.ecr.aws/m3u4c4h9/island-is/actions-runner-public:latest
     timeout-minutes: 30
-    strategy:
-      fail-fast: false
-      matrix:
-        agent:
-          - '1'
-          - '2'
-          - '3'
+    defaults:
+      run:
+        working-directory: ${{ github.workspace }}
+        # Specify shell to help normalize across different operating systems
+        shell: bash
+    if: contains(github.event.pull_request.labels.*.name, 'nx-cloud')
     steps:
       - uses: actions/checkout@v3
         with:
@@ -170,8 +174,7 @@ jobs:
           echo "HEAD=$NX_HEAD" >> $GITHUB_ENV
           echo "NX_BRANCH=$BRANCH_NAME" >> $GITHUB_ENV
           echo "[DEBUG] BRANCH_NAME: $BRANCH_NAME"
-      - name: Setup Node
-        uses: actions/setup-node@v3
+      - uses: actions/setup-node@v3
         with:
           node-version: '18.8.0'
       - name: Calculate cache key for node_modules
@@ -226,11 +229,25 @@ jobs:
       - name: Untar generated files
         run: tar zxvf generated_files.tar.gz
 
-      - name: Start Nx Agent ${{ matrix.agent }}
-        run: npx nx-cloud start-agent
-        env:
-          NX_AGENT_NAME: ${{matrix.agent}}
-
+      - name: nx-affected
+        run: |
+          pids=()
+          npx nx affected --base="$BASE" --head="$HEAD" --target lint --parallel="$MAX_JOBS" "$@" &
+          pids+=($!)
+          npx nx affected --base="$BASE" --head="$HEAD" --target build --parallel="$MAX_JOBS" "$@" &
+          pids+=($!)
+          for pid in \${pids[*]}; do
+            if ! wait $pid; then
+              exit 1
+            fi
+          done
+          exit 0
+      - name: Stop all running agents for this CI run
+        # It's important that we always run this step, otherwise in the case of any failures in preceding non-Nx steps, the agents will keep running and waste billable minutes
+        if: ${{ always() }}
+        run: npx nx-cloud stop-all-agents
+      - name: fix hanging post job
+        run: git config --local --get remote.origin.url
   # check-matrix:
   #   runs-on: ec2-runners
   #   container:
