ci: nx distributed agents

diff --git a/.github/workflows/pullrequest-nx-cloud.yml b/.github/workflows/pullrequest-nx-cloud.yml
--- a/.github/workflows/pullrequest-nx-cloud.yml
+++ b/.github/workflows/pullrequest-nx-cloud.yml
@@ -32,7 +32,10 @@ env:
   USE_NX_CLOUD: ${{ contains(github.event.pull_request.labels.*.name, 'nx-cloud') }}
   MAX_JOBS: 30
   BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
-
+  NX_BRANCH: ${{ github.head_ref || github.ref_name }}
+  NX_TARGETS: 'lint build'
+  NX_CLOUD_DISTRIBUTED_EXECUTION: true
+  NX_CLOUD_DISTRIBUTED_EXECUTION_AGENT_COUNT: 3
 jobs:
   nx:
     runs-on: ec2-runners
@@ -41,48 +44,49 @@ jobs:
     timeout-minutes: 30
     strategy:
       fail-fast: false
-      matrix:
-        nx-target:
-          - build
-          - lint
+      # matrix:
+      #   nx-target:
+      #     - build
+      #     - lint
     if: contains(github.event.pull_request.labels.*.name, 'nx-cloud')
     steps:
       - uses: actions/checkout@v3
         with:
           fetch-depth: 0
-      - name: Generate matrix output
-        run: |
-          matrix=$((
-            echo '${{ toJSON(matrix) }}'
-          ) | jq -c .)
-          echo "$matrix" > matrix
-          echo "matrix: $matrix"
-          echo "::set-output name=matrix::$matrix"
-        id: matrix
-      - name: Upload matrix
-        uses: actions/upload-artifact@v3
-        id: upload-matrix
-        with:
-          name: ${{ hashFiles('matrix') || 'none' }}
-          path: matrix
-          if-no-files-found: warn
-      - uses: actions/upload-artifact@v3
-        with:
-          name: ${{ hashFiles('matrix') || 'none' }}
-          path: matrix
-          if-no-files-found: warn
+      # - name: Generate matrix output
+      #   run: |
+      #     matrix=$((
+      #       echo '${{ toJSON(matrix) }}'
+      #     ) | jq -c .)
+      #     echo "$matrix" > matrix
+      #     echo "matrix: $matrix"
+      #     echo "::set-output name=matrix::$matrix"
+      #   id: matrix
+      # - name: Upload matrix
+      #   uses: actions/upload-artifact@v3
+      #   id: upload-matrix
+      #   with:
+      #     name: ${{ hashFiles('matrix') || 'none' }}
+      #     path: matrix
+      #     if-no-files-found: warn
+      # - uses: actions/upload-artifact@v3
+      #   with:
+      #     name: ${{ hashFiles('matrix') || 'none' }}
+      #     path: matrix
+      #     if-no-files-found: warn
       - uses: nrwl/nx-set-shas@v3
       - run: |
           echo "BASE=$NX_BASE" >> $GITHUB_ENV
           echo "HEAD=$NX_HEAD" >> $GITHUB_ENV
           echo "NX_BRANCH=$BRANCH_NAME" >> $GITHUB_ENV
           echo "[DEBUG] BRANCH_NAME: $BRANCH_NAME"
-      - uses: actions/setup-node@v3
+      # - uses: actions/setup-node@v3
+      #   with:
+      #     node-version: '18'
+      - name: Setup Node
+        uses: volta-cli/action@v4
         with:
-          node-version: '18'
-      - name: Setup yarn
-        run: npm install -g yarn
-
+          package-json-path: '${{ github.workspace }}/package.json'
       - name: Calculate cache key for node_modules
         id: calculate_node_modules_hash
         run: |
@@ -137,25 +141,104 @@ jobs:
 
       - name: Building
         run: |
-          MAX_JOBS=2 ./scripts/ci/run-nx-affected.sh ${{ matrix.nx-target }}
+          MAX_JOBS=2 ./scripts/ci/run-nx-affected.sh ${{ env.NX_TARGETS }}
+
+      - name: Stop all running agents for this CI run
+        # It's important that we always run this step, otherwise in the case of any failures in preceding non-Nx steps, the agents will keep running and waste billable minutes
+        if: ${{ always() }}
+        run: npx nx-cloud stop-all-agents
+
       - name: fix hanging post job
         run: git config --local --get remote.origin.url
 
-  check-matrix:
+  agents:
+    name: Agent ${{ matrix.agent }}
     runs-on: ec2-runners
     container:
       image: public.ecr.aws/m3u4c4h9/island-is/actions-runner-public:latest
-    needs: [nx]
-    outputs:
-      matrix: ${{ steps.matrix.outputs.matrix }}
+    timeout-minutes: 30
+    strategy:
+      fail-fast: false
+      matrix:
+        agent:
+          - [1, 2, 3]
     steps:
-      - uses: actions/download-artifact@v3
-      - run: |
-          echo "Check matrix"
-          matrix="$(cat */matrix | jq -c --slurp .)"
-          echo "matrix: $matrix"
-          echo "::set-output name=matrix::$matrix"
-        id: matrix
+      - name: Setup Node
+        uses: volta-cli/action@v4
+        with:
+          package-json-path: '${{ github.workspace }}/package.json'
+      - name: Calculate cache key for node_modules
+        id: calculate_node_modules_hash
+        run: |
+          PACKAGE_JSON_HASH=$(cat package.json | jq '{resolutions,dependencies,devDependencies}' | sha1sum -t | cut -f1 -d" ")
+          echo "PACKAGE_JSON_HASH: $PACKAGE_JSON_HASH"
+          NODE_MODULES_HASH=${{ runner.os }}-${{ hashFiles('yarn.lock') }}-$PACKAGE_JSON_HASH
+          echo "NODE_MODULES_HASH: $NODE_MODULES_HASH"
+          echo "NODE_MODULES_HASH=$NODE_MODULES_HASH" >> $GITHUB_ENV
+
+      - name: Calculate cache keys for generated files
+        id: calculate_generated_files_cache_key
+        run: |
+          export HASH=${{ hashFiles('scripts/schemas.js', 'libs/cms/src/lib/generated/contentfulTypes.d.ts', 'apps/air-discount-scheme/web/i18n/withLocale.tsx', 'apps/air-discount-scheme/web/components/AppLayout/AppLayout.tsx', 'apps/air-discount-scheme/web/components/Header/Header.tsx', 'apps/air-discount-scheme/web/screens/**.tsx', 'apps/**/codegen.yml', 'libs/**/codegen.yml', 'apps/**/*.model.ts', 'libs/**/*.model.ts', 'apps/**/*.enum.ts', 'libs/**/*.enum.ts', 'apps/**/queries/**/*.tsx?', 'libs/**/queries/**/*.tsx?', 'libs/**/mutations/**/*.tsx?', 'libs/**/fragments/**/*.tsx?' , 'apps/**/*.resolver.ts', 'libs/**/*.resolver.ts', 'apps/**/*.service.ts', 'libs/**/*.service.ts', 'apps/**/*.dto.ts', 'libs/**/*.dto.ts', 'apps/**/*.input.ts', 'libs/**/*.input.ts', 'apps/**/*.module.ts', 'libs/**/*.module.ts', 'apps/**/*.controller.ts', 'libs/**/*.controller.ts', 'apps/**/*.union.ts', 'libs/**/*.union.ts', 'apps/**/*.graphql.ts', 'libs/**/*.graphql.ts', 'libs/**/*.graphql') }}
+          GENERATED_FILES_KEY=${{ runner.os }}-$HASH-files-generated
+          echo "GENERATED_FILES_KEY: $GENERATED_FILES_KEY"
+          echo "GENERATED_FILES_KEY=$GENERATED_FILES_KEY" >> $GITHUB_ENV
+
+      - name: Cache for NodeJS dependencies - host OS
+        id: node-modules
+        continue-on-error: true
+        uses: ./.github/actions/cache
+        with:
+          path: node_modules
+          key: ${{ env.NODE_MODULES_HASH }}-yarn
+
+      - name: Check cache success
+        run: '[[ "${{ steps.node-modules.outputs.success }}" != "false" ]] || exit 1'
+
+      - name: Cache for generated files
+        id: generated-files-cache
+        continue-on-error: true
+        uses: ./.github/actions/cache
+        with:
+          path: generated_files.tar.gz
+          key: ${{ env.GENERATED_FILES_KEY }}
+
+      - name: Check cache success
+        run: '[[ "${{ steps.generated-files-cache.outputs.success }}" != "false" ]] || exit 1'
+
+      - name: Building NodeJS dependencies
+        if: steps.node-modules.outputs.cache-hit != 'true'
+        run: ./scripts/ci/10_prepare-host-deps.sh
+
+      - name: Generate schemas
+        if: steps.generated-files-cache.outputs.cache-hit != 'true'
+        run: |
+          node --version
+          tar zcvf generated_files.tar.gz $(./scripts/ci/get-files-touched-by.sh yarn schemas --skip-cache | xargs realpath --relative-to $(pwd))
+
+      - name: Untar generated files
+        run: tar zxvf generated_files.tar.gz
+
+      - name: Start Nx Agent ${{ matrix.agent }}
+        run: npx nx-cloud start-agent
+        env:
+          NX_AGENT_NAME: ${{matrix.agent}}
+
+  # check-matrix:
+  #   runs-on: ec2-runners
+  #   container:
+  #     image: public.ecr.aws/m3u4c4h9/island-is/actions-runner-public:latest
+  #   needs: [nx]
+  #   outputs:
+  #     matrix: ${{ steps.matrix.outputs.matrix }}
+  #   steps:
+  #     - uses: actions/download-artifact@v3
+  #     - run: |
+  #         echo "Check matrix"
+  #         matrix="$(cat */matrix | jq -c --slurp .)"
+  #         echo "matrix: $matrix"
+  #         echo "::set-output name=matrix::$matrix"
+  #       id: matrix
 
   # TODO: trying to dynamically get the the matrix result output, unfinished
   # success:
