Test

diff --git a/.github/workflows/pullrequest.yml b/.github/workflows/pullrequest.yml
--- a/.github/workflows/pullrequest.yml
+++ b/.github/workflows/pullrequest.yml
@@ -295,10 +295,19 @@ jobs:
       - name: Setup yarn
         run: corepack enable
 
-      - name: Install Root Dependencies
-        run: yarn install --immutable
+      - name: Cache for NodeJS dependencies
+        id: node-modules
+        continue-on-error: true
+        uses: ./.github/actions/cache
+        with:
+          path: infra/node_modules
+          key: ${{ runner.os }}-${{ hashFiles('infra/yarn.lock') }}-infra
 
-      - name: Install Infra Dependencies
+      - name: Check cache success
+        run: '[[ "${{ steps.node-modules.outputs.success }}" != "false" ]] || exit 1'
+
+      - name: Building NodeJS dependencies
+        if: steps.node-modules.outputs.cache-hit != 'true'
         working-directory: infra
         run: yarn install --immutable
 
@@ -390,68 +399,76 @@ jobs:
           ./infra/scripts/ci/git-check-dirty.sh "/" "nx format:write" "dirtybot"
 
   linting:
-    needs:
-      - prepare
+    if: false
     runs-on: ec2-runners
-    container:
-      image: public.ecr.aws/m3u4c4h9/island-is/actions-runner-public:latest
-    timeout-minutes: 35
-    if: needs.prepare.outputs.LINT_CHUNKS
-    env:
-      AFFECTED_PROJECTS: ${{ matrix.projects }}
-      NODE_OPTIONS: --max-old-space-size=4096
-      MAX_JOBS: 3
-    strategy:
-      fail-fast: false
-      matrix: ${{ fromJson(needs.prepare.outputs.LINT_CHUNKS) }}
     steps:
-      - uses: actions/checkout@v4
-      - uses: actions/setup-node@v4
-        with:
-          node-version-file: 'package.json'
-      - name: Setup yarn
-        run: corepack enable
-      - name: Get cache
-        id: get-cache
-        uses: ./.github/actions/get-cache
-        with:
-          github-token: ${{ secrets.GITHUB_TOKEN }}
-          keys: ${{ needs.prepare.outputs.CACHE_KEYS }}
-          enable-cache: 'node_modules,generated-files'
-      - name: Linting
-        run: ./scripts/ci/run-in-parallel-native.sh lint
+      - run: echo "This step won't run"
+    # needs:
+    #   - prepare
+    # runs-on: ec2-runners
+    # container:
+    #   image: public.ecr.aws/m3u4c4h9/island-is/actions-runner-public:latest
+    # timeout-minutes: 35
+    # if: needs.prepare.outputs.LINT_CHUNKS
+    # env:
+    #   AFFECTED_PROJECTS: ${{ matrix.projects }}
+    #   NODE_OPTIONS: --max-old-space-size=4096
+    #   MAX_JOBS: 3
+    # strategy:
+    #   fail-fast: false
+    #   matrix: ${{ fromJson(needs.prepare.outputs.LINT_CHUNKS) }}
+    # steps:
+    #   - uses: actions/checkout@v4
+    #   - uses: actions/setup-node@v4
+    #     with:
+    #       node-version-file: 'package.json'
+    #   - name: Setup yarn
+    #     run: corepack enable
+    #   - name: Get cache
+    #     id: get-cache
+    #     uses: ./.github/actions/get-cache
+    #     with:
+    #       github-token: ${{ secrets.GITHUB_TOKEN }}
+    #       keys: ${{ needs.prepare.outputs.CACHE_KEYS }}
+    #       enable-cache: 'node_modules,generated-files'
+    #   - name: Linting
+    #     run: ./scripts/ci/run-in-parallel-native.sh lint
 
   build:
-    needs:
-      - prepare
+    if: false
     runs-on: ec2-runners
-    container:
-      image: public.ecr.aws/m3u4c4h9/island-is/actions-runner-public:latest
-    timeout-minutes: 35
-    env:
-      AFFECTED_PROJECTS: ${{ matrix.projects }}
-      MAX_JOBS: 2
-    strategy:
-      fail-fast: false
-      matrix: ${{ fromJson(needs.prepare.outputs.BUILD_CHUNKS) }}
-    if: needs.prepare.outputs.BUILD_CHUNKS
     steps:
-      - uses: actions/checkout@v4
-      - uses: actions/setup-node@v4
-        with:
-          node-version-file: 'package.json'
-      - name: Setup yarn
-        run: corepack enable
-      - name: Get cache
-        id: get-cache
-        uses: ./.github/actions/get-cache
-        with:
-          github-token: ${{ secrets.GITHUB_TOKEN }}
-          keys: ${{ needs.prepare.outputs.CACHE_KEYS }}
-          enable-cache: 'node_modules,generated-files'
+      - run: echo "This step won't run"
+    # needs:
+    #   - prepare
+    # runs-on: ec2-runners
+    # container:
+    #   image: public.ecr.aws/m3u4c4h9/island-is/actions-runner-public:latest
+    # timeout-minutes: 35
+    # env:
+    #   AFFECTED_PROJECTS: ${{ matrix.projects }}
+    #   MAX_JOBS: 2
+    # strategy:
+    #   fail-fast: false
+    #   matrix: ${{ fromJson(needs.prepare.outputs.BUILD_CHUNKS) }}
+    # if: needs.prepare.outputs.BUILD_CHUNKS
+    # steps:
+    #   - uses: actions/checkout@v4
+    #   - uses: actions/setup-node@v4
+    #     with:
+    #       node-version-file: 'package.json'
+    #   - name: Setup yarn
+    #     run: corepack enable
+    #   - name: Get cache
+    #     id: get-cache
+    #     uses: ./.github/actions/get-cache
+    #     with:
+    #       github-token: ${{ secrets.GITHUB_TOKEN }}
+    #       keys: ${{ needs.prepare.outputs.CACHE_KEYS }}
+    #       enable-cache: 'node_modules,generated-files'
 
-      - name: Building
-        run: ./scripts/ci/run-in-parallel-native.sh build
+    #   - name: Building
+    #     run: ./scripts/ci/run-in-parallel-native.sh build
 
   success:
     runs-on: ec2-runners
