Move newlints into linting

diff --git a/.github/workflows/pullrequest.yml b/.github/workflows/pullrequest.yml
--- a/.github/workflows/pullrequest.yml
+++ b/.github/workflows/pullrequest.yml
@@ -233,78 +233,6 @@ jobs:
       #     ./scripts/ci/20_check-formatting.sh "write"
       #     ./infra/scripts/ci/git-check-dirty.sh "/" "nx format:write" "dirtybot"
 
-  newlints:
-    needs:
-      - prepare
-    runs-on: arc-runners
-    timeout-minutes: 35
-    if: ${{ needs.prepare.outputs.LINT_CHUNKS && !contains(github.event.pull_request.labels.*.name, 'dirty bypass') }}
-    env:
-      AFFECTED_PROJECTS: ${{ matrix.projects }}
-      NODE_OPTIONS: --max-old-space-size=4096
-      NX_BASE: ${{ needs.prepare.outputs.NX_BASE }}
-    strategy:
-      fail-fast: false
-      matrix: ${{ fromJson(needs.prepare.outputs.LINT_CHUNKS) }}
-    steps:
-      - uses: actions/checkout@v4
-        if: ${{ github.event_name == 'pull_request' }}
-        with:
-          token: ${{ secrets.DIRTY_FIX_BOT_TOKEN }}
-          ref: ${{ github.event.pull_request.head.ref }}
-      - name: Setup yarn
-        uses: ./.github/actions/setup-yarn
-        with:
-          RUNS_ON_S3_BUCKET_CACHE: ${{ secrets.S3_DOCKER_CACHE_BUCKET }}
-      - name: load-deps
-        uses: ./.github/actions/load-deps
-      - name: Verify lint doesn't fail
-        env:
-          NX_SKIP_NX_CACHE: true
-        run: set -x; yarn nx run-many -t lint --projects "$AFFECTED_PROJECTS"
-      # - uses: actions/checkout@v4
-      #   with:
-      #     ref: ${{ github.event.pull_request.head.ref }}
-      - name: Lint head
-        id: lint-head
-        env:
-          NX_SKIP_NX_CACHE: true
-        run: |
-          lints=$(yarn nx run-many -t lint --projects "$AFFECTED_PROJECTS") || echo "There was an error while linting, ignoring"
-          echo "$lints" | wc -l | xargs -I% echo "lint-lines=%" | tee -a "$GITHUB_OUTPUT"
-          echo "lints<<EOF" >> "$GITHUB_OUTPUT"
-          echo "$lints" >> "$GITHUB_OUTPUT"
-          echo "EOF" >> "$GITHUB_OUTPUT"
-      - uses: actions/checkout@v4
-        with:
-          ref: ${{ github.event.pull_request.base.ref }}
-      - name: Lint base
-        id: lint-base
-        env:
-          NX_SKIP_NX_CACHE: true
-        run: |
-          lints=$(yarn nx run-many -t lint --projects "$AFFECTED_PROJECTS") || echo "There was an error while linting, ignoring"
-          echo "$lints" | wc -l | xargs -I% echo "lint-lines=%" | tee -a "$GITHUB_OUTPUT"
-          echo "lints<<EOF" >> "$GITHUB_OUTPUT"
-          echo "$lints" >> "$GITHUB_OUTPUT"
-          echo "EOF" >> "$GITHUB_OUTPUT"
-      - name: No new lint lines
-        env:
-          HEAD_LINTS: ${{steps.lint-head.outputs.lints}}
-          BASE_LINTS: ${{steps.lint-base.outputs.lints}}
-          HEAD_LINT_COUNT: ${{steps.lint-head.outputs.lint-lines || 0}}
-          BASE_LINT_COUNT: ${{steps.lint-base.outputs.lint-lines || 0}}
-        run: |
-          if (( HEAD_LINT_COUNT <= BASE_LINT_COUNT )); then
-            echo "Lint count has not increased"
-            exit 0
-          fi
-          echo "::error title=Found $((HEAD_LINT_COUNT - BASE_LINT_COUNT)) additional lint lines::Please fix your lints 🙏"
-          echo "::group::lintdiff"
-          diff <(echo "$BASE_LINTS") <(echo "$HEAD_LINTS")
-          echo "::endgroup::"
-          exit 1
-
   lintfix-changed-files:
     name: Lintfix Changed Files
     runs-on: arc-runners
@@ -364,8 +292,43 @@ jobs:
       - name: load-deps
         uses: ./.github/actions/load-deps
 
-      - name: Linting
-        run: ./scripts/ci/run-in-parallel-native.sh lint
+      # Don't need to check out the current PR branch
+      # - uses: actions/checkout@v4
+      #   with:
+      #     ref: ${{ github.event.pull_request.head.ref }}
+      - name: Lint head
+        id: lint-head
+        run: |
+          echo "lints<<EOF" | tee -a "$GITHUB_OUTPUT"
+          yarn nx run-many -t lint --output-style=static --projects "$AFFECTED_PROJECTS" | tee -a "$GITHUB_OUTPUT"
+          echo "EOF" | tee -a "$GITHUB_OUTPUT"
+      - uses: actions/checkout@v4
+        with:
+          ref: ${{ github.event.pull_request.base.ref }}
+      - name: Lint base
+        id: lint-base
+        run: |
+          echo "lints<<EOF" | tee -a "$GITHUB_OUTPUT"
+          yarn nx run-many -t lint --projects "$AFFECTED_PROJECTS" | tee -a "$GITHUB_OUTPUT"
+          echo "EOF" | tee -a "$GITHUB_OUTPUT"
+      - name: No new lints
+        env:
+          HEAD_LINTS: ${{steps.lint-head.outputs.lints}}
+          BASE_LINTS: ${{steps.lint-base.outputs.lints}}
+        run: |
+          # Divide by 2 because each problem summary occurs twice
+          HEAD_LINT_COUNT="$(( $(echo "$HEAD_LINTS" | grep -oP '(?<=✖ )(\d+)(?= problems)') / 2))"
+          BASE_LINT_COUNT="$(( $(echo "$BASE_LINTS" | grep -oP '(?<=✖ )(\d+)(?= problems)') / 2))"
+          COUNT_DIFF=$(( HEAD_LINT_COUNT <= BASE_LINT_COUNT )) || :
+          if [[ $COUNT_DIFF -eq 0 ]]; then
+            echo "Lint count has not increased"
+            exit 0
+          fi
+          echo "::error title=Found $COUNT_DIFF additional lint lines::Please fix your lints 🙏"
+          echo "::group::lintdiff"
+          diff <(echo "$BASE_LINTS") <(echo "$HEAD_LINTS") || :
+          echo "::endgroup::"
+          exit 1
 
   build:
     needs:
