set -x

diff --git a/.github/workflows/pullrequest.yml b/.github/workflows/pullrequest.yml
--- a/.github/workflows/pullrequest.yml
+++ b/.github/workflows/pullrequest.yml
@@ -261,7 +261,7 @@ jobs:
       - name: Verify lint doesn't fail
         env:
           NX_SKIP_NX_CACHE: true
-        run: yarn nx run-many -t lint --projects "$AFFECTED_PROJECTS"
+        run: set -x; yarn nx run-many -t lint --projects "$AFFECTED_PROJECTS"
       # - uses: actions/checkout@v4
       #   with:
       #     ref: ${{ github.event.pull_request.head.ref }}
@@ -269,7 +269,7 @@ jobs:
         id: lint-head
         env:
           NX_SKIP_NX_CACHE: true
-        run: yarn nx run-many -t lint --projects "$AFFECTED_PROJECTS" | wc -l | xargs -I% echo "lint-lines=%" | tee -a "$GITHUB_OUTPUT" || echo "There was an error while linting, ignoring"
+        run: set -x; yarn nx run-many -t lint --projects "$AFFECTED_PROJECTS" | wc -l | xargs -I% echo "lint-lines=%" | tee -a "$GITHUB_OUTPUT" || echo "There was an error while linting, ignoring"
       - uses: actions/checkout@v4
         with:
           ref: ${{ github.event.pull_request.base.ref }}
@@ -277,7 +277,7 @@ jobs:
         id: lint-base
         env:
           NX_SKIP_NX_CACHE: true
-        run: yarn nx run-many -t lint --projects "$AFFECTED_PROJECTS" | wc -l | xargs -I% echo "lint-lines=%" | tee -a "$GITHUB_OUTPUT" || echo "There was an error while linting, ignoring"
+        run: set -x; yarn nx run-many -t lint --projects "$AFFECTED_PROJECTS" | wc -l | xargs -I% echo "lint-lines=%" | tee -a "$GITHUB_OUTPUT" || echo "There was an error while linting, ignoring"
       - name: No new lint lines
         env:
           HEAD_LINTS: ${{steps.lint-head.outputs.lint-lines}}
