Revert "revert: "feat(ci): Run `lint --fix` with dirtybot (#17538)" (#17617)"
This reverts commit 27c57efd9a93964d3e6a134fce356bbabda43138.

diff --git a/.github/workflows/pullrequest.yml b/.github/workflows/pullrequest.yml
--- a/.github/workflows/pullrequest.yml
+++ b/.github/workflows/pullrequest.yml
@@ -382,6 +382,11 @@ jobs:
       matrix: ${{ fromJson(needs.prepare.outputs.LINT_CHUNKS) }}
     steps:
       - uses: actions/checkout@v4
+        if: ${{ github.event_name == 'pull_request' }}
+        # Needed for doing git commit in git-check-dirty script
+        with:
+          token: ${{ secrets.DIRTY_FIX_BOT_TOKEN }}
+          ref: ${{ github.event.pull_request.head.ref }}
       - uses: actions/setup-node@v4
         with:
           node-version-file: 'package.json'
@@ -394,6 +399,19 @@ jobs:
           github-token: ${{ secrets.GITHUB_TOKEN }}
           keys: ${{ needs.prepare.outputs.CACHE_KEYS }}
           enable-cache: 'node_modules,generated-files'
+      - name: Lintfix
+        if: ${{ !contains(github.event.pull_request.labels.*.name, 'dirty bypass') }}
+        run: |
+          set -euo pipefail
+          echo "Running lint --fix for affected projects: ${AFFECTED_PROJECTS}"
+          ./infra/scripts/ci/git-check-dirty.sh \
+            -p "/" \
+            -a "nx run-many --target lint --fix --parallel ${MAX_JOBS} --projects=${AFFECTED_PROJECTS//[[\]]}" \
+            -o "dirtybot" \
+            -r || {
+              echo "Error: Lintfix failed. Check the logs above for details." >&2
+              exit 1
+            }
       - name: Linting
         run: ./scripts/ci/run-in-parallel-native.sh lint
 
