Ignore errors in lint

diff --git a/.github/workflows/pullrequest.yml b/.github/workflows/pullrequest.yml
--- a/.github/workflows/pullrequest.yml
+++ b/.github/workflows/pullrequest.yml
@@ -265,9 +265,7 @@ jobs:
         id: lint-base
         env:
           NX_SKIP_NX_CACHE: true
-        run: |
-          set -x
-          yarn nx run-many -t lint --projects "$AFFECTED_PROJECTS" | wc -l | xargs -I% echo "lint-lines=%" | tee -a "$GITHUB_OUTPUT"
+        run: yarn nx run-many -t lint --projects "$AFFECTED_PROJECTS" | wc -l | xargs -I% echo "lint-lines=%" | tee -a "$GITHUB_OUTPUT" || echo "There was an error while linting, ignoring"
       - uses: actions/checkout@v4
         with:
           ref: ${{ github.event.pull_request.head.ref }}
@@ -275,9 +273,7 @@ jobs:
         id: lint-head
         env:
           NX_SKIP_NX_CACHE: true
-        run: |
-          set -x
-          yarn nx run-many -t lint --projects "$AFFECTED_PROJECTS" | wc -l | xargs -I% echo "lint-lines=%" | tee -a "$GITHUB_OUTPUT"
+        run: yarn nx run-many -t lint --projects "$AFFECTED_PROJECTS" | wc -l | xargs -I% echo "lint-lines=%" | tee -a "$GITHUB_OUTPUT" || echo "There was an error while linting, ignoring"
       - name: No new lint lines
         run: |
           if (( ${{steps.lint-head.output.lint-lines}} >= ${{steps.lint-base.output.lint-lines}} )); then
