Use jq filtering for better output and uniform dependency checking

diff --git a/.github/workflows/pullrequest.yml b/.github/workflows/pullrequest.yml
--- a/.github/workflows/pullrequest.yml
+++ b/.github/workflows/pullrequest.yml
@@ -393,26 +393,31 @@ jobs:
       - build
       - unicorn-tests
     steps:
-      - name: Check prepare success
-        run: '[[ ${{ needs.prepare.result }} == "success" ]] || exit 1'
       - name: Notify about deploy-feature label
         if: ${{ github.event.pull_request.auto_merge && needs.prepare.outputs.DEPLOY_FEATURE == 'true' }}
         run: |
           echo "- 👉 Remove the \`deploy-feature\` label if you want this PR to be merged automatically" >> $GITHUB_STEP_SUMMARY
           exit 1
-      - name: Check tests success
-        run: '[[ ${{ needs.tests.result }} != "failure" ]] || exit 1'
-      - name: Check e2e success
-        run: '[[ ${{ needs.e2e.result }} != "failure" ]] || exit 1'
-      - name: Check linting success
-        run: '[[ ${{ needs.linting.result }} != "failure" ]] || exit 1'
-      - name: Check run-shellcheck success
-        run: '[[ ${{ needs.run-shellcheck.result }} != "failure" ]] || exit 1'
-      - name: Check formatting success
-        run: '[[ ${{ needs.formatting.result }} != "failure" ]] || exit 1'
-      - name: Check build success
-        run: '[[ ${{ needs.build.result }} != "failure" ]] || exit 1'
-      - name: Check Unicorn test success
-        run: '[[ ${{ needs.unicorn-tests.result }} != "failure" ]] || exit 1'
+
+      - name: Collect
+        env:
+          NEEDS: ${{ toJSON(needs) }}
+        run: |
+          echo -n "Dependencies succeeded? "
+          if ! jq -ne --argjson needs "$NEEDS" '$needs | to_entries | map_values(select(.result != "success")) | length == 0'; then
+            failed_dependencies=$(jq -n --argjson needs "$NEEDS" -r '
+              [
+                  $needs
+                | to_entries
+                | map_values(select(.result != "success"))
+                | .[]
+                | "\(.key) (\(.value.result))"
+              ]
+              | join(", ")')
+            echo "::error title=NEEDS::Some dependencies failed: $failed_dependencies"
+            exit 1
+          fi
+          exit 0
+
       - name: Announce success
         run: echo "Build is successful"
