fixes

diff --git a/.github/workflows/pullrequest.yml b/.github/workflows/pullrequest.yml
--- a/.github/workflows/pullrequest.yml
+++ b/.github/workflows/pullrequest.yml
@@ -332,21 +332,21 @@ jobs:
           HEAD_LINT_FILE: ${{steps.lint-head.outputs.lints-file}}
           BASE_LINT_FILE: ${{steps.lint-base.outputs.lints-file}}
         run: |
-          COUNT_DIFF=$(( HEAD_LINT_COUNT - BASE_LINT_COUNT )) || :
-          if (( COUNT_DIFF <= 0 )); then
-            echo "Lint count has not increased"
-            exit 0
-          fi
-          echo "::error title=NEW_LINTS::Please fix your lints 🙏 (found $COUNT_DIFF additional lints)"
-
           # Get `<filename> #lints: <n>` lines for easy diff
-          for f in "${HEAD_LINT_FILE}" "${BASE_LINT_FILE}"; do
+          for f in "${BASE_LINT_FILE}" "${HEAD_LINT_FILE}"; do
             # Make "Remote cache..." and "Local cache" be the same
             sed -i -E 's/\[[^]]*cache[^]*]\]/[cached]/g' "${f}"
             grep -oP "(?<=$PWD/).*" "${f}" | sort -n | uniq -c | awk '{print($2 " #lints: " $1)}' > "${f}_files.out"
           done
+          NEW_LINTS=$(comm -13 "${BASE_LINT_FILE}_files.out" "${HEAD_LINT_FILE}_files.out" | wc -l)
+          COUNT_DIFF=$(( HEAD_LINT_COUNT - BASE_LINT_COUNT )) || :
+          if (( COUNT_DIFF <= 0 )) || [[ "$NEW_LINTS" -gt 0 ]]; then
+            echo "Lint count has not increased"
+            exit 0
+          fi
+          echo "::error title=NEW_LINTS::Please fix your lints 🙏 (found $COUNT_DIFF additional lints)"
           echo "Files with changed lints:"
-          diff "${HEAD_LINT_FILE}_files.out" "${BASE_LINT_FILE}_files.out" || :
+          diff "${BASE_LINT_FILE}_files.out" "${HEAD_LINT_FILE}_files.out" || :
           echo "::group::lintdiff"
           diff "${BASE_LINT_FILE}" "${HEAD_LINT_FILE}" || : # Ignore diff exit code
           echo "::endgroup::"
