ci: improve success job for features

diff --git a/.github/workflows/pullrequest.yml b/.github/workflows/pullrequest.yml
--- a/.github/workflows/pullrequest.yml
+++ b/.github/workflows/pullrequest.yml
@@ -639,13 +639,10 @@ jobs:
       - name: Check prepare success
         run: '[[ ${{ needs.prepare.result }} == "success" ]] || exit 1'
       - name: Check if deploy-feature is enabled
+        if: ${{ needs.prepare.outputs.DEPLOY_FEATURE }}" == 'true'
         run: |
-          if [ "$DEPLOY_FEATURE" == "true" ]; then
-            echo "::error::The deploy-feature flag is currently enabled, remove it before merge."
-            exit 1
-          else
-            echo "::notice::Deploy-feature flag is not enabled. Proceeding with the workflow."
-          fi
+          echo "::error::The deploy-feature flag is currently enabled, remove it before merge."
+          exit 1
       - name: Check tests success
         run: '[[ ${{ needs.tests.result }} != "failure" ]] || exit 1'
       - name: Check e2e success
