fix: jq parse

diff --git a/.github/workflows/push.yml b/.github/workflows/push.yml
--- a/.github/workflows/push.yml
+++ b/.github/workflows/push.yml
@@ -223,9 +223,9 @@ jobs:
           set -euo pipefail
           CHUNKS="$(./scripts/ci/generate-docker-chunks.sh docker-express docker-next docker-static docker-playwright docker-jest)"
           echo "CHUNKS: '$CHUNKS'"
+          echo "CHUNKS_NO_QUOTE: $CHUNKS"
           if [[ "$CHUNKS" != "[]" ]]; then
-            echo BUILD_CHUNKS=$(echo "$CHUNKS" | jq -cM '. | map("\(.|tostring)")') >> "$GITHUB_OUTPUT"
-            echo "CHUNKS='$CHUNKS'" >> "$GITHUB_OUTPUT"
+            echo "BUILD_CHUNKS='$CHUNKS'" >> "$GITHUB_OUTPUT"
           fi
 
       # NOTE: only on PRs
@@ -234,12 +234,12 @@ jobs:
         if: needs.pre-checks.outputs.PRE_CHECK != 'push'
         run: |
           set -euo pipefail
-          CHUNKS=${{ steps.build_map.outputs.CHUNKS }}
-          echo "CHUNKS: '$CHUNKS'"
-          if [[ "$CHUNKS" != "[]" ]]; then
+          BUILD_CHUNKS=${{ steps.build_map.outputs.BUILD_CHUNKS }}
+          echo "BUILD_CHUNKS: $BUILD_CHUNKS"
+          if [[ "$BUILD_CHUNKS" != "[]" ]]; then
             # NOTE: validate the jq command to trigger failure
-            echo "$CHUNKS" | jq -r 'map(.projects) | join(",")'
-            IMAGES=$(echo "$CHUNKS" | jq -r 'map(.projects) | join(",")')
+            echo "$BUILD_CHUNKS" | jq -r 'map(.projects) | join(",")'
+            IMAGES=$(echo "$BUILD_CHUNKS" | jq -r 'map(.projects) | join(",")')
             echo "IMAGES='$IMAGES'" >> "$GITHUB_OUTPUT"
           fi
 
@@ -268,9 +268,9 @@ jobs:
         if: steps.build_map.outputs.BUILD_CHUNKS
         env:
           GIT_COMMIT_SHA: ${{ github.sha }}
+          BUILD_CHUNKS: ${{ steps.build_map.outputs.BUILD_CHUNKS }}
         run: |
           set -euo pipefail
-          BUILD_CHUNKS='${{ steps.build_map.outputs.CHUNKS }}'
           echo "$BUILD_CHUNKS"
 
           # Prepare common Docker build arguments
@@ -304,6 +304,10 @@ jobs:
             DOCKER_TYPE="$(echo "$chunk" | jq -r '.docker_type')"
             APP_HOME="$(echo "$chunk" | jq -r '.home')"
             APP_DIST_HOME="$(echo "$chunk" | jq -r '.dist')"
+            if [[ "$APP_DIST_HOME" == "null" || -z "$APP_DIST_HOME" || "$APP_DIST_HOME" == "" ]]; then
+              echo "Error: Project '$AFFECTED_PROJECTS' has an invalid dist filepath: '$APP_DIST_HOME'"
+              exit 1
+            fi
 
             # Create a build script for this chunk
             cat > .buildkit-commands/build-${chunk_index}.sh << EOF
@@ -322,7 +326,6 @@ jobs:
           done
 
           # Execute all builds in parallel using GNU Parallel
-          # Adjust the -j flag based on your runner resources
           find .buildkit-commands -name "build-*.sh" | parallel -j 8
 
   # docker-build:
