Use /home/runner

diff --git a/.github/actions/setup-yarn/action.yml b/.github/actions/setup-yarn/action.yml
--- a/.github/actions/setup-yarn/action.yml
+++ b/.github/actions/setup-yarn/action.yml
@@ -4,30 +4,12 @@ description: 'Yarn setup and install dependencies. This is our authoritative pla
 runs:
   using: 'composite'
   steps:
-    - name: Prep env
-      shell: bash
-      env:
-        YARN_CACHE_FOLDER: $HOME/dependencies/.yarn/cache
-        CYPRESS_CACHE_FOLDER: $HOME/dependencies/.cache
-        COREPACK_HOME: $HOME/dependencies/corepack
-        NODE_PATH: $HOME/dependencies/node_modules
-        COREPACK_ENABLE_STRICT: 1
-      run: |
-        for e in YARN_CACHE_FOLDER CYPRESS_CACHE_FOLDER COREPACK_HOME NODE_PATH COREPACK_ENABLE_STRICT; do
-          if ! env | grep "^${e}=.*"; then echo "${e} not found in env"; continue; fi
-          # Expand home-dirs with string substitution (matches homes at the beginning of the variable)
-          p=${!e}
-          p=${p/#\$HOME/$HOME}
-          p=${p/#\~/$HOME}
-          echo "${e}=${p}" | tee -a "$GITHUB_ENV"
-        done
-
     - name: Compare yarn.lock files
       shell: bash
       id: compare_yarn_lock
       run: |
         current=$(sha256sum yarn.lock | awk '{print $1}')
-        bundled=$(sha256sum "$HOME/dependencies/yarn.lock" | awk '{print $1}') || echo "Failed reading bundled yarn.lock, ignoring..."
+        bundled=$(sha256sum "/home/runner/dependencies/yarn.lock" | awk '{print $1}') || echo "Failed reading bundled yarn.lock, ignoring..."
         skip_install=$([ "$current" = "$bundled" ] && echo true || echo false)
         echo "Current hash: $current"
         echo "Bundled hash: $bundled"
@@ -50,10 +32,10 @@ runs:
       run: |
         yarn install --immutable
         (
-          cp -rf ./node_modules "$HOME/dependencies/node_modules"
-          cp -rf ./.yarn "$HOME/dependencies/.yarn"
-          cp -rf ./yarn.lock "$HOME/dependencies/yarn.lock"
-          cp -rf ./package.json "$HOME/dependencies/package.json"
+          cp -rf ./node_modules "/home/runner/dependencies/node_modules"
+          cp -rf ./.yarn "/home/runner/dependencies/.yarn"
+          cp -rf ./yarn.lock "/home/runner/dependencies/yarn.lock"
+          cp -rf ./package.json "/home/runner/dependencies/package.json"
         ) || echo "Failed copying back to dependencies
 
     - name: Link pre-installed dependencies
@@ -61,7 +43,7 @@ runs:
       shell: bash
       run: |
         rm -rf node_modules
-        ln -sf "$HOME/dependencies/node_modules" .
-        ln -sf "$HOME/dependencies/.yarn/cache" .yarn/
-        ln -sf "$HOME/dependencies/.yarn/install-state.gz" .yarn/
-        echo "NODE_PATH=$HOME/dependencies/node_modules:$NODE_PATH" >> $GITHUB_ENV
+        ln -sf "/home/runner/dependencies/node_modules" .
+        ln -sf "/home/runner/dependencies/.yarn/cache" .yarn/
+        ln -sf "/home/runner/dependencies/.yarn/install-state.gz" .yarn/
+        echo "NODE_PATH=/home/runner/dependencies/node_modules:$NODE_PATH" >> $GITHUB_ENV
