ci: setup pullthrough on yarn registry server

diff --git a/.github/actions/setup-yarn/action.yml b/.github/actions/setup-yarn/action.yml
--- a/.github/actions/setup-yarn/action.yml
+++ b/.github/actions/setup-yarn/action.yml
@@ -4,6 +4,18 @@ inputs:
   RUNS_ON_S3_BUCKET_CACHE:
     description: ''
     required: true
+  YARN_NPM_REGISTRY_SERVER:
+    description: ''
+    required: false
+    default: ''
+  AWS_ACCOUNT_ID:
+    description: ''
+    required: false
+    default: '821090935708'
+  AWS_REGION:
+    description: ''
+    required: false
+    default: 'eu-west-1'
   working-directory:
     description: 'Directory to run the action in'
     required: false
@@ -26,6 +38,32 @@ runs:
         node -v
         yarn --version
         ls -l "$(which node)"
+
+    - name: Setup NPM pull-through
+      shell: bash
+      run: |
+        inital_registry_server=$(yarn config get npmRegistryServer)
+        echo "inital_registry_server $inital_registry_server"
+
+        # aws sts get-caller-identity
+        ble=$(aws sts get-caller-identity)
+        echo "AWS call identity $ble"
+
+        yarn config set npmRegistryServer "${{ inputs.YARN_NPM_REGISTRY_SERVER }}"
+
+        CODEARTIFACT_AUTH_TOKEN="$(aws codeartifact get-authorization-token --domain npm-upstream \
+          --domain-owner ${{ inputs.AWS_ACCOUNT_ID }} --region ${{ inputs.AWS_REGION }} \
+          --query authorizationToken --output text)"
+
+        export CODEARTIFACT_AUTH_TOKEN="$CODEARTIFACT_AUTH_TOKEN"
+
+        [ "${CODEARTIFACT_AUTH_TOKEN}" != "" ] && echo "We have token" || echo "Token missing"
+
+        yarn config set 'npmRegistries["${{ inputs.YARN_NPM_REGISTRY_SERVER }}"].npmAuthToken' "${CODEARTIFACT_AUTH_TOKEN}"
+        yarn config set 'npmRegistries["${{ inputs.YARN_NPM_REGISTRY_SERVER }}"].npmAlwaysAuth' "true"
+
+        val=$(yarn config get 'npmRegistries["${{ inputs.YARN_NPM_REGISTRY_SERVER }}"]')
+        echo "Value from yarn config get npmRegistries $val"
 
     - name: Set cache key
       working-directory: ${{ inputs.working-directory }}
