Move env to where they're used, not globally in several scripts

diff --git a/.github/actions/setup-yarn/action.yml b/.github/actions/setup-yarn/action.yml
--- a/.github/actions/setup-yarn/action.yml
+++ b/.github/actions/setup-yarn/action.yml
@@ -4,12 +4,29 @@ description: 'Yarn setup and install dependencies'
 runs:
   using: 'composite'
   steps:
+    - name: Prep env
+      shell: bash
+      env:
+        # Yarn cache needs a folder that exists, and will fail otherwise
+        YARN_CACHE_FOLDER: ${{ github.event.localrun && '$HOME/dependencies/.yarn/cache' || '' }}
+        COREPACK_HOME: $HOME/dependencies/corepack
+        NODE_PATH: $HOME/dependencies/node_modules
+      run: |
+        set -x
+        for e in YARN_CACHE_FOLDER COREPACK_HOME NODE_PATH; do
+          if p=$(realpath "${!e}"); then
+            echo "${e}=${p}" >> "$GITHUB_ENV"
+          else
+            echo "Using ${e} defaults (not set explicitly)"
+          fi
+        done
+
     - name: Compare yarn.lock files
       shell: bash
       id: compare_yarn_lock
       run: |
         current=$(sha256sum yarn.lock | awk '{print $1}')
-        bundled=$(sha256sum ~/dependencies/yarn.lock | awk '{print $1}') || :
+        bundled=$(sha256sum "$HOME/dependencies/yarn.lock" | awk '{print $1}') || :
         skip_install=$([ "$current" = "$bundled" ] && echo true || echo false)
         echo "Current hash: $current"
         echo "Bundled hash: $bundled"
@@ -34,7 +51,7 @@ runs:
       shell: bash
       run: |
         rm -rf node_modules
-        ln -s ~/dependencies/node_modules .
-        ln -s ~/dependencies/.yarn/cache .yarn/
-        ln -s ~/dependencies/.yarn/install-state.gz .yarn/
+        ln -s "$HOME/dependencies/node_modules" .
+        ln -s "$HOME/dependencies/.yarn/cache" .yarn/
+        ln -s "$HOME/dependencies/.yarn/install-state.gz" .yarn/
         echo "NODE_PATH=$HOME/dependencies/node_modules:$NODE_PATH" >> $GITHUB_ENV
